### PR TITLE
Make the updater simple and use v2x of QAppImageUpdate

### PR DESCRIPTION
**Pull request by antony-jr**
This PR gives the inbuilt updater a very simple and intuitive GUI and uses much less code. This PR requires QAppImageUpdate v2.x

The Result would look something as show in the below video,

https://user-images.githubusercontent.com/33930174/110531823-0e240b80-8142-11eb-8fa7-17e399360a15.mp4

### CODE REVIEW

**Comment by luzpaz** [comment]
Yes please!

**Comment by looooo** [comment]
Thanks. @antony-jr do you want direct access to this repo and to the feedstock?

**Comment by antony-jr** [comment]
> Thanks. @antony-jr do you want direct access to this repo and to the feedstock?

That might come handy for future updates and fixes.

**Comment by luzpaz** [comment]
//cc @realthunder

**Pull request merged**
